### ISSUE TITLE
Error on transport creation for incoming connection

### ISSUE THREAD

**Issue by stcro84** [openlumi/homeassistant_on_openwrt#38]
Hello.
I have installed Homeassistant from branch 23.05 on my system:

> Raspberry Pi 3 Model B Rev 1.2
> OpenWrt 23.05.0 r23497-6637af95aa / LuCI openwrt-23.05 branch git-23.236.53405-fc638c8

The installation was performed on a clean system by running <ha_install.sh> without errors. Services homeassistant and hass-configurator are started properly after reboot and running. I can access hass-configurator locally on port 3218, but can't access homeassistant on port 8123.
Here is error part of homeassistant debug log:

> 2024-01-02 08:25:39.271 ERROR (MainThread) [homeassistant] Error doing job: Error on transport creation for incoming connection
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/asyncio/selector_events.py", line 208, in _accept_connection2
>   File "/usr/lib/python3.11/site-packages/aiohttp/web_server.py", line 62, in __call__
> TypeError: RequestHandler.__init__() got an unexpected keyword argument 'handler_cancellation'

Beside that, I tried installation from branch 21.05 and it works.
Can you help, what could be wrong with 23.05?

**Comment by devbis** [comment]
Hi! Branch 23.05 is in progress with the same issues that you have. But it seems that this message is a clue. A went into the same results while using --debug mode. Maybe the working version will be released soon.

**Comment by devbis** [comment]
@stusun84 Today I made required changes to make 2023.12 runnable on 23.05. Can you please check the script from that branch again? It's not thoroughly tested yet, so I'll appreciate any feedback.

**Comment by stcro84** [comment]
Hello. Nice to hear that you are working on 23.05. 
I have checked the script again, first by stopping services homeassistant and hass-configurator, and than running it over my existing (broken) installation. Now, the initial ERROR is gone but have some others, here is the complete log:

> root@OpenWrt:~# cat /var/log/home-assistant.log
2024-01-05 08:05:31.988 ERROR (MainThread) [homeassistant.setup] Setup failed for 'analytics': Unable to import component: No module named 'psutil_home_assistant'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/homeassistant/components/analytics/__init__.py", line 13, in <module>
    from .analytics import Analytics
  File "/usr/lib/python3.11/site-packages/homeassistant/components/analytics/analytics.py", line 16, in <module>
    from homeassistant.components.energy import (
  File "/usr/lib/python3.11/site-packages/homeassistant/components/energy/__init__.py", line 10, in <module>
    from . import websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/energy/websocket_api.py", line 15, in <module>
    from homeassistant.components import recorder, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/__init__.py", line 28, in <module>
    from . import entity_registry, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/entity_registry.py", line 8, in <module>
    from .core import Recorder
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/core.py", line 16, in <module>
    import psutil_home_assistant as ha_psutil
ModuleNotFoundError: No module named 'psutil_home_assistant'
2024-01-05 08:05:32.049 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'onboarding'. Setup failed for dependencies: analytics
2024-01-05 08:05:32.050 ERROR (MainThread) [homeassistant.setup] Setup failed for 'onboarding': (DependencyError(...), 'Could not setup dependencies: analytics')
2024-01-05 08:05:32.052 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'frontend'. Setup failed for dependencies: onboarding
2024-01-05 08:05:32.052 ERROR (MainThread) [homeassistant.setup] Setup failed for 'frontend': (DependencyError(...), 'Could not setup dependencies: onboarding')
2024-01-05 08:05:32.063 ERROR (MainThread) [homeassistant.setup] Setup failed for 'recorder': Unable to import component: No module named 'psutil_home_assistant'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/__init__.py", line 28, in <module>
    from . import entity_registry, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/entity_registry.py", line 8, in <module>
    from .core import Recorder
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/core.py", line 16, in <module>
    import psutil_home_assistant as ha_psutil
ModuleNotFoundError: No module named 'psutil_home_assistant'
2024-01-05 08:05:33.308 ERROR (MainThread) [homeassistant.setup] Setup failed for 'hardware': Unable to import component: No module named 'psutil_home_assistant'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/homeassistant/components/hardware/__init__.py", line 8, in <module>
    from . import websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/hardware/websocket_api.py", line 9, in <module>
    import psutil_home_assistant as ha_psutil
ModuleNotFoundError: No module named 'psutil_home_assistant'
2024-01-05 08:05:33.698 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'my'. Setup failed for dependencies: frontend
2024-01-05 08:05:33.699 ERROR (MainThread) [homeassistant.setup] Setup failed for 'my': (DependencyError(...), 'Could not setup dependencies: frontend')
2024-01-05 08:05:33.701 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'map'. Setup failed for dependencies: frontend
2024-01-05 08:05:33.701 ERROR (MainThread) [homeassistant.setup] Setup failed for 'map': (DependencyError(...), 'Could not setup dependencies: frontend')
2024-01-05 08:05:33.842 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'logbook'. Setup failed for dependencies: frontend, recorder
2024-01-05 08:05:33.842 ERROR (MainThread) [homeassistant.setup] Setup failed for 'logbook': (DependencyError(...), 'Could not setup dependencies: frontend, recorder')
2024-01-05 08:05:33.849 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'panel_iframe'. Setup failed for dependencies: frontend
2024-01-05 08:05:33.849 ERROR (MainThread) [homeassistant.setup] Setup failed for 'panel_iframe': (DependencyError(...), 'Could not setup dependencies: frontend')
2024-01-05 08:05:33.850 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'history'. Setup failed for dependencies: recorder
2024-01-05 08:05:33.851 ERROR (MainThread) [homeassistant.setup] Setup failed for 'history': (DependencyError(...), 'Could not setup dependencies: recorder')
2024-01-05 08:05:34.171 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'energy'. Setup failed for dependencies: history, recorder
2024-01-05 08:05:34.172 ERROR (MainThread) [homeassistant.setup] Setup failed for 'energy': (DependencyError(...), 'Could not setup dependencies: history, recorder')
2024-01-05 08:05:35.147 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: energy, frontend, hardware, history, logbook, map, my
2024-01-05 08:05:35.148 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': (DependencyError(...), 'Could not setup dependencies: energy, frontend, hardware, history, logbook, map, my')
2024-01-05 08:05:35.150 WARNING (MainThread) [homeassistant.bootstrap] Detected that frontend did not load. Activating recovery mode
2024-01-05 08:05:35.209 ERROR (MainThread) [homeassistant.setup] Setup failed for 'recovery_mode': Integration not found.
 
I don't know if I should uninstall my previous installation before trying the updated script?
Thank you.

**Comment by devbis** [comment]
Looks like I missed installing `psutil_home_assistant` and just installed it manually. 
I modified the script as well as updated to the latest 2024.1 version. 
Can you please re-run the script again?

**Comment by stcro84** [comment]
I have tested it, still doesn't work.
It seams that now sqlalchemy is missing:

> root@OpenWrt:~# cat /var/log/home-assistant.log
2024-01-05 23:12:15.446 ERROR (MainThread) [homeassistant.setup] Setup failed for 'analytics': Unable to import compo                                                                                                                        nent: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/homeassistant/components/analytics/__init__.py", line 13, in <module>
    from .analytics import Analytics
  File "/usr/lib/python3.11/site-packages/homeassistant/components/analytics/analytics.py", line 16, in <module>
    from homeassistant.components.energy import (
  File "/usr/lib/python3.11/site-packages/homeassistant/components/energy/__init__.py", line 10, in <module>
    from . import websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/energy/websocket_api.py", line 15, in <module>
    from homeassistant.components import recorder, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/__init__.py", line 28, in <module>
    from . import entity_registry, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/entity_registry.py", line 8, in <module>
    from .core import Recorder
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/core.py", line 17, in <module>
    from sqlalchemy import create_engine, event as sqlalchemy_event, exc, select
ModuleNotFoundError: No module named 'sqlalchemy'
2024-01-05 23:12:15.507 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'onboarding'. Setup                                                                                                                         failed for dependencies: analytics
2024-01-05 23:12:15.508 ERROR (MainThread) [homeassistant.setup] Setup failed for 'onboarding': (DependencyError(...)                                                                                                                        , 'Could not setup dependencies: analytics')
2024-01-05 23:12:15.509 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'frontend'. Setup f                                                                                                                        ailed for dependencies: onboarding
2024-01-05 23:12:15.510 ERROR (MainThread) [homeassistant.setup] Setup failed for 'frontend': (DependencyError(...),                                                                                                                         'Could not setup dependencies: onboarding')
2024-01-05 23:12:15.522 ERROR (MainThread) [homeassistant.setup] Setup failed for 'recorder': Unable to import compon                                                                                                                        ent: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/__init__.py", line 28, in <module>
    from . import entity_registry, websocket_api
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/entity_registry.py", line 8, in <module>
    from .core import Recorder
  File "/usr/lib/python3.11/site-packages/homeassistant/components/recorder/core.py", line 17, in <module>
    from sqlalchemy import create_engine, event as sqlalchemy_event, exc, select
ModuleNotFoundError: No module named 'sqlalchemy'
2024-01-05 23:12:17.543 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'panel_iframe'. Set                                                                                                                        up failed for dependencies: frontend
2024-01-05 23:12:17.543 ERROR (MainThread) [homeassistant.setup] Setup failed for 'panel_iframe': (DependencyError(..                                                                                                                        .), 'Could not setup dependencies: frontend')
2024-01-05 23:12:17.544 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'history'. Setup fa                                                                                                                        iled for dependencies: recorder
2024-01-05 23:12:17.544 ERROR (MainThread) [homeassistant.setup] Setup failed for 'history': (DependencyError(...), '                                                                                                                        Could not setup dependencies: recorder')
2024-01-05 23:12:17.545 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'my'. Setup failed                                                                                                                         for dependencies: frontend
2024-01-05 23:12:17.546 ERROR (MainThread) [homeassistant.setup] Setup failed for 'my': (DependencyError(...), 'Could                                                                                                                         not setup dependencies: frontend')
2024-01-05 23:12:17.560 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'map'. Setup failed                                                                                                                         for dependencies: frontend
2024-01-05 23:12:17.561 ERROR (MainThread) [homeassistant.setup] Setup failed for 'map': (DependencyError(...), 'Coul                                                                                                                        d not setup dependencies: frontend')
2024-01-05 23:12:17.561 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'logbook'. Setup fa                                                                                                                        iled for dependencies: frontend, recorder
2024-01-05 23:12:17.562 ERROR (MainThread) [homeassistant.setup] Setup failed for 'logbook': (DependencyError(...), '                                                                                                                        Could not setup dependencies: frontend, recorder')
2024-01-05 23:12:17.820 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'energy'. Setup fai                                                                                                                        led for dependencies: history, recorder
2024-01-05 23:12:17.821 ERROR (MainThread) [homeassistant.setup] Setup failed for 'energy': (DependencyError(...), 'C                                                                                                                        ould not setup dependencies: history, recorder')
2024-01-05 23:12:18.901 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. S                                                                                                                        etup failed for dependencies: energy, frontend, history, logbook, map, my
2024-01-05 23:12:18.902 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': (DependencyError(                                                                                                                        ...), 'Could not setup dependencies: energy, frontend, history, logbook, map, my')
2024-01-05 23:12:18.917 WARNING (MainThread) [homeassistant.bootstrap] Detected that frontend did not load. Activatin                                                                                                                        g recovery mode
2024-01-05 23:12:18.972 ERROR (MainThread) [homeassistant.setup] Setup failed for 'recovery_mode': Integration not fo                                                                                                                        und.

I have installed it manually and after that it works,
Please add it to install script.

**Comment by stcro84** [comment]
After reboot and initial HA setup, I have some other errors in my system, here is the log:
> root@OpenWrt:~# cat /var/log/home-assistant.log
> 2024-01-05 23:26:49.407 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration songpal
> 2024-01-05 23:26:49.532 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 2076, in _load_integration
>     integration = await loader.async_get_integration(hass, domain)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/loader.py", line 904, in async_get_integration
>     raise int_or_exc
> homeassistant.loader.IntegrationNotFound: Integration 'songpal' not found.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/site-packages/homeassistant/helpers/discovery_flow.py", line 96, in _async_start
>     await gather_with_limited_concurrency(
>   File "/usr/lib/python3.11/site-packages/homeassistant/util/async_.py", line 188, in gather_with_limited_concurrency
>     return await gather(
>            ^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/util/async_.py", line 186, in sem_task
>     return await task
>            ^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 888, in async_init
>     flow, result = await task
>                    ^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 906, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 1009, in async_create_flow
>     handler = await _async_get_flow_handler(
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 2106, in _async_get_flow_handler
>     await _load_integration(hass, domain, hass_config)
>   File "/usr/lib/python3.11/site-packages/homeassistant/config_entries.py", line 2079, in _load_integration
>     raise data_entry_flow.UnknownHandler from err
> homeassistant.data_entry_flow.UnknownHandler
> 2024-01-05 23:26:49.730 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration braviatv
> 2024-01-05 23:26:49.731 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration dlna_dmr
> root@OpenWrt:~#

**Comment by devbis** [comment]
Thanks, also missed adding sqlachemy while installing manually.

Are these errors regarding braviatv,songpal block ha from loading or the UI is accessible?
